spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fxwallet?currentSchema=fxwallet}
    username: ${SPRING_DATASOURCE_USERNAME:fxwallet}
    password: ${SPRING_DATASOURCE_PASSWORD:fxwallet}
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:fxwallet}
  flyway:
    schemas: ${DB_SCHEMA:fxwallet}
    default-schema: ${DB_SCHEMA:fxwallet}
